services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8080"
      - "2345:2345"
    volumes:
      - ./:/app
    networks:
      - internal
    restart: always
    deploy:
      resources:
        limits:
          memory: 6G
  db:
    image: groonga/pgroonga:latest-alpine-16
    shm_size: 1g
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 30
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      # - ./database.sql:/docker-entrypoint-initdb.d/database.sql
      - ./stuff/TMDB_movie_dataset_v11.csv:/stuff/TMDB_movie_dataset_v11.csv
      - ./stuff/Torrents.csv:/stuff/Torrents.csv
      - ./stuff/torrent_match.csv:/stuff/torrent_match.csv
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - internal
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
volumes:
  pgdata:
  redisdata:
networks:
  internal:
    driver: bridge
