services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    volumes:
      - gluetun-data:/tmp/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - SERVER_COUNTRIES=Singapore,Hong Kong,Taiwan,Japan
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_PROVIDER=protonvpn
      - WIREGUARD_MTU=1280
      - WIREGUARD_ADDRESSES=10.2.0.2/32
      - BLOCK_MALICIOUS=off
      - VERSION_INFORMATION=off
      - HEALTH_TARGET_ADDRESSES=cloudflare.com,google.com
    ports:
      - "8080:8080/tcp"
      - "2345:2345/tcp"
      - "39810:39810/tcp"
      - "39810:39810/udp"
    networks:
      - internal
    restart: always

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    environment:
      - TERM=xterm-256color
    env_file:
      - .env
    volumes:
      - ./:/app
      - gluetun-data:/tmp/gluetun:ro
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always
    deploy:
      resources:
        limits:
          memory: 6G
  db:
    image: groonga/pgroonga:latest-alpine-16
    shm_size: 1g
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 30
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./stuff/TMDB_movie_dataset_v11.csv:/stuff/TMDB_movie_dataset_v11.csv
      - ./stuff/Torrents.csv:/stuff/Torrents.csv
      - ./stuff/torrent_match.csv:/stuff/torrent_match.csv

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - internal
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pgdata:
  redisdata:
  gluetun-data:
networks:
  internal:
    driver: bridge
