// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package repository

import (
	"context"
)

// iteratorForBulkInsertTorrentContents implements pgx.CopyFromSource.
type iteratorForBulkInsertTorrentContents struct {
	rows                 []BulkInsertTorrentContentsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkInsertTorrentContents) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkInsertTorrentContents) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Infohash,
		r.rows[0].TorrentName,
		r.rows[0].ContentName,
		r.rows[0].ParsedContentName,
		r.rows[0].SizeBytes,
		r.rows[0].MatchID,
	}, nil
}

func (r iteratorForBulkInsertTorrentContents) Err() error {
	return nil
}

func (q *Queries) BulkInsertTorrentContents(ctx context.Context, arg []BulkInsertTorrentContentsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"torrent_contents"}, []string{"infohash", "torrent_name", "content_name", "parsed_content_name", "size_bytes", "match_id"}, &iteratorForBulkInsertTorrentContents{rows: arg})
}
