// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type TmdbMovieDatasetV11 struct {
	ID                  int32          `json:"id"`
	Title               string         `json:"title"`
	VoteAverage         pgtype.Numeric `json:"vote_average"`
	VoteCount           pgtype.Int4    `json:"vote_count"`
	Status              pgtype.Text    `json:"status"`
	ReleaseDate         string         `json:"release_date"`
	Revenue             pgtype.Int8    `json:"revenue"`
	Runtime             pgtype.Int4    `json:"runtime"`
	Adult               pgtype.Bool    `json:"adult"`
	BackdropPath        string         `json:"backdrop_path"`
	Budget              pgtype.Int8    `json:"budget"`
	Homepage            string         `json:"homepage"`
	ImdbID              pgtype.Text    `json:"imdb_id"`
	OriginalLanguage    pgtype.Text    `json:"original_language"`
	OriginalTitle       string         `json:"original_title"`
	Overview            string         `json:"overview"`
	Popularity          pgtype.Numeric `json:"popularity"`
	PosterPath          string         `json:"poster_path"`
	Tagline             string         `json:"tagline"`
	Genres              string         `json:"genres"`
	ProductionCompanies string         `json:"production_companies"`
	ProductionCountries string         `json:"production_countries"`
	SpokenLanguages     string         `json:"spoken_languages"`
	Keywords            string         `json:"keywords"`
}

type Torrent struct {
	Infohash    string             `json:"infohash"`
	Name        string             `json:"name"`
	SizeBytes   int64              `json:"size_bytes"`
	CreatedUnix pgtype.Int8        `json:"created_unix"`
	Seeders     pgtype.Int4        `json:"seeders"`
	Leechers    pgtype.Int4        `json:"leechers"`
	Completed   pgtype.Int4        `json:"completed"`
	ScrapedDate pgtype.Timestamptz `json:"scraped_date"`
	Published   pgtype.Timestamptz `json:"published"`
}

type TorrentContent struct {
	ID          pgtype.Int4 `json:"id"`
	Infohash    string      `json:"infohash"`
	TorrentName string      `json:"torrent_name"`
	ContentName string      `json:"content_name"`
	SizeBytes   int64       `json:"size_bytes"`
	MatchID     pgtype.Int4 `json:"match_id"`
}
