// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type BulkInsertTorrentContentsParams struct {
	Infohash    string      `json:"infohash"`
	TorrentName string      `json:"torrent_name"`
	ContentName string      `json:"content_name"`
	SizeBytes   int64       `json:"size_bytes"`
	MatchID     pgtype.Int4 `json:"match_id"`
}

const getUnmatchedTorrents = `-- name: GetUnmatchedTorrents :many
SELECT t.infohash FROM torrents t WHERE NOT EXISTS ( SELECT 1 FROM torrent_contents tc WHERE tc.infohash = t.infohash) ORDER BY t.seeders DESC
`

func (q *Queries) GetUnmatchedTorrents(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getUnmatchedTorrents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var infohash string
		if err := rows.Scan(&infohash); err != nil {
			return nil, err
		}
		items = append(items, infohash)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTorrentContent = `-- name: InsertTorrentContent :one
INSERT INTO torrent_contents (infohash, torrent_name, content_name, size_bytes, match_id) VALUES ($1, $2, $3, $4, $5) ON CONFLICT DO NOTHING RETURNING id, infohash, torrent_name, content_name, size_bytes, match_id
`

type InsertTorrentContentParams struct {
	Infohash    string      `json:"infohash"`
	TorrentName string      `json:"torrent_name"`
	ContentName string      `json:"content_name"`
	SizeBytes   int64       `json:"size_bytes"`
	MatchID     pgtype.Int4 `json:"match_id"`
}

func (q *Queries) InsertTorrentContent(ctx context.Context, arg InsertTorrentContentParams) (TorrentContent, error) {
	row := q.db.QueryRow(ctx, insertTorrentContent,
		arg.Infohash,
		arg.TorrentName,
		arg.ContentName,
		arg.SizeBytes,
		arg.MatchID,
	)
	var i TorrentContent
	err := row.Scan(
		&i.ID,
		&i.Infohash,
		&i.TorrentName,
		&i.ContentName,
		&i.SizeBytes,
		&i.MatchID,
	)
	return i, err
}

const searchMoviesByTitleAndYear = `-- name: SearchMoviesByTitleAndYear :one
SELECT id
FROM (
    SELECT 
        id,
        popularity,
        (
            similarity(title, $1) + 
            CASE WHEN $2::text != '' AND release_date LIKE $2::text || '%' THEN 0.2 ELSE 0.0 END
        ) AS score
    FROM tmdb_movie_dataset_v11
    WHERE title % $1
) sub
WHERE score > 0.5
ORDER BY score DESC, popularity DESC
LIMIT 1
`

type SearchMoviesByTitleAndYearParams struct {
	Title       string `json:"title"`
	ReleaseYear string `json:"release_year"`
}

func (q *Queries) SearchMoviesByTitleAndYear(ctx context.Context, arg SearchMoviesByTitleAndYearParams) (int32, error) {
	row := q.db.QueryRow(ctx, searchMoviesByTitleAndYear, arg.Title, arg.ReleaseYear)
	var id int32
	err := row.Scan(&id)
	return id, err
}
