// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"
)

type Querier interface {
	BulkInsertTorrentContents(ctx context.Context, arg []BulkInsertTorrentContentsParams) (int64, error)
	GetUnmatchedTorrents(ctx context.Context) ([]string, error)
	InsertTorrentContent(ctx context.Context, arg InsertTorrentContentParams) (TorrentContent, error)
	SearchMoviesByTitleAndYear(ctx context.Context, arg SearchMoviesByTitleAndYearParams) (int32, error)
}

var _ Querier = (*Queries)(nil)
